name: Telegram notification

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          ${{ github.actor }} performed ${{ github.event_name }} on ${{ github.repository }}:
          ${{ github.event_path }}
