name: Telegram notification

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: -1001414132454
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          The ${{ github.event_name }} event triggered first step.
