name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          The ${{ github.event_name }} event triggered first step.
          echo ${{ secrets.TELEGRAM_TO }}
